// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: v1/aibrain_service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AIBrainService_SubmitAsyncTask_FullMethodName        = "/aibrain.AIBrainService/SubmitAsyncTask"
	AIBrainService_GetAsyncTask_FullMethodName           = "/aibrain.AIBrainService/GetAsyncTask"
	AIBrainService_GetAsyncTasks_FullMethodName          = "/aibrain.AIBrainService/GetAsyncTasks"
	AIBrainService_CancelAsyncTask_FullMethodName        = "/aibrain.AIBrainService/CancelAsyncTask"
	AIBrainService_UploadComfyUIInputFile_FullMethodName = "/aibrain.AIBrainService/UploadComfyUIInputFile"
	AIBrainService_ChatStream_FullMethodName             = "/aibrain.AIBrainService/ChatStream"
	AIBrainService_HealthCheck_FullMethodName            = "/aibrain.AIBrainService/HealthCheck"
)

// AIBrainServiceClient is the client API for AIBrainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIBrainServiceClient interface {
	// SubmitAsyncTask 提交一个异步生成任务
	// 用于创建图片、视频等耗时较长的生成任务
	SubmitAsyncTask(ctx context.Context, in *SubmitAsyncTaskRequest, opts ...grpc.CallOption) (*SubmitAsyncTaskResponse, error)
	// GetAsyncTask 获取指定异步任务的状态和结果
	// 通过任务ID查询单个任务的详细信息
	GetAsyncTask(ctx context.Context, in *GetAsyncTaskRequest, opts ...grpc.CallOption) (*GetAsyncTaskResponse, error)
	// GetAsyncTasks 批量获取异步任务状态
	// 支持通过任务ID列表或状态过滤器批量查询任务
	GetAsyncTasks(ctx context.Context, in *GetAsyncTasksRequest, opts ...grpc.CallOption) (*GetAsyncTasksResponse, error)
	// CancelAsyncTask 取消指定的异步任务
	// 尝试取消正在执行或等待执行的任务
	CancelAsyncTask(ctx context.Context, in *CancelAsyncTaskRequest, opts ...grpc.CallOption) (*CancelAsyncTaskResponse, error)
	// UploadInputFile 上传文件到input目录下，作为后续入参使用(Cloud ComfyUI 执行器下使用)
	UploadComfyUIInputFile(ctx context.Context, in *UploadComfyUIInputFileRequest, opts ...grpc.CallOption) (*UploadComfyUIInputFileResponse, error)
	// ChatStream 进行流式聊天对话
	// 提供实时的文本生成和对话功能，支持服务器端流式响应
	ChatStream(ctx context.Context, in *ChatStreamRequest, opts ...grpc.CallOption) (AIBrainService_ChatStreamClient, error)
	// HealthCheck 健康检查
	// 用于检查服务的可用性和健康状态
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type aIBrainServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIBrainServiceClient(cc grpc.ClientConnInterface) AIBrainServiceClient {
	return &aIBrainServiceClient{cc}
}

func (c *aIBrainServiceClient) SubmitAsyncTask(ctx context.Context, in *SubmitAsyncTaskRequest, opts ...grpc.CallOption) (*SubmitAsyncTaskResponse, error) {
	out := new(SubmitAsyncTaskResponse)
	err := c.cc.Invoke(ctx, AIBrainService_SubmitAsyncTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIBrainServiceClient) GetAsyncTask(ctx context.Context, in *GetAsyncTaskRequest, opts ...grpc.CallOption) (*GetAsyncTaskResponse, error) {
	out := new(GetAsyncTaskResponse)
	err := c.cc.Invoke(ctx, AIBrainService_GetAsyncTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIBrainServiceClient) GetAsyncTasks(ctx context.Context, in *GetAsyncTasksRequest, opts ...grpc.CallOption) (*GetAsyncTasksResponse, error) {
	out := new(GetAsyncTasksResponse)
	err := c.cc.Invoke(ctx, AIBrainService_GetAsyncTasks_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIBrainServiceClient) CancelAsyncTask(ctx context.Context, in *CancelAsyncTaskRequest, opts ...grpc.CallOption) (*CancelAsyncTaskResponse, error) {
	out := new(CancelAsyncTaskResponse)
	err := c.cc.Invoke(ctx, AIBrainService_CancelAsyncTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIBrainServiceClient) UploadComfyUIInputFile(ctx context.Context, in *UploadComfyUIInputFileRequest, opts ...grpc.CallOption) (*UploadComfyUIInputFileResponse, error) {
	out := new(UploadComfyUIInputFileResponse)
	err := c.cc.Invoke(ctx, AIBrainService_UploadComfyUIInputFile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIBrainServiceClient) ChatStream(ctx context.Context, in *ChatStreamRequest, opts ...grpc.CallOption) (AIBrainService_ChatStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &AIBrainService_ServiceDesc.Streams[0], AIBrainService_ChatStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &aIBrainServiceChatStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AIBrainService_ChatStreamClient interface {
	Recv() (*ChatStreamResponse, error)
	grpc.ClientStream
}

type aIBrainServiceChatStreamClient struct {
	grpc.ClientStream
}

func (x *aIBrainServiceChatStreamClient) Recv() (*ChatStreamResponse, error) {
	m := new(ChatStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aIBrainServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, AIBrainService_HealthCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIBrainServiceServer is the server API for AIBrainService service.
// All implementations must embed UnimplementedAIBrainServiceServer
// for forward compatibility
type AIBrainServiceServer interface {
	// SubmitAsyncTask 提交一个异步生成任务
	// 用于创建图片、视频等耗时较长的生成任务
	SubmitAsyncTask(context.Context, *SubmitAsyncTaskRequest) (*SubmitAsyncTaskResponse, error)
	// GetAsyncTask 获取指定异步任务的状态和结果
	// 通过任务ID查询单个任务的详细信息
	GetAsyncTask(context.Context, *GetAsyncTaskRequest) (*GetAsyncTaskResponse, error)
	// GetAsyncTasks 批量获取异步任务状态
	// 支持通过任务ID列表或状态过滤器批量查询任务
	GetAsyncTasks(context.Context, *GetAsyncTasksRequest) (*GetAsyncTasksResponse, error)
	// CancelAsyncTask 取消指定的异步任务
	// 尝试取消正在执行或等待执行的任务
	CancelAsyncTask(context.Context, *CancelAsyncTaskRequest) (*CancelAsyncTaskResponse, error)
	// UploadInputFile 上传文件到input目录下，作为后续入参使用(Cloud ComfyUI 执行器下使用)
	UploadComfyUIInputFile(context.Context, *UploadComfyUIInputFileRequest) (*UploadComfyUIInputFileResponse, error)
	// ChatStream 进行流式聊天对话
	// 提供实时的文本生成和对话功能，支持服务器端流式响应
	ChatStream(*ChatStreamRequest, AIBrainService_ChatStreamServer) error
	// HealthCheck 健康检查
	// 用于检查服务的可用性和健康状态
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedAIBrainServiceServer()
}

// UnimplementedAIBrainServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAIBrainServiceServer struct {
}

func (UnimplementedAIBrainServiceServer) SubmitAsyncTask(context.Context, *SubmitAsyncTaskRequest) (*SubmitAsyncTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitAsyncTask not implemented")
}
func (UnimplementedAIBrainServiceServer) GetAsyncTask(context.Context, *GetAsyncTaskRequest) (*GetAsyncTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAsyncTask not implemented")
}
func (UnimplementedAIBrainServiceServer) GetAsyncTasks(context.Context, *GetAsyncTasksRequest) (*GetAsyncTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAsyncTasks not implemented")
}
func (UnimplementedAIBrainServiceServer) CancelAsyncTask(context.Context, *CancelAsyncTaskRequest) (*CancelAsyncTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelAsyncTask not implemented")
}
func (UnimplementedAIBrainServiceServer) UploadComfyUIInputFile(context.Context, *UploadComfyUIInputFileRequest) (*UploadComfyUIInputFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadComfyUIInputFile not implemented")
}
func (UnimplementedAIBrainServiceServer) ChatStream(*ChatStreamRequest, AIBrainService_ChatStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ChatStream not implemented")
}
func (UnimplementedAIBrainServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedAIBrainServiceServer) mustEmbedUnimplementedAIBrainServiceServer() {}

// UnsafeAIBrainServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIBrainServiceServer will
// result in compilation errors.
type UnsafeAIBrainServiceServer interface {
	mustEmbedUnimplementedAIBrainServiceServer()
}

func RegisterAIBrainServiceServer(s grpc.ServiceRegistrar, srv AIBrainServiceServer) {
	s.RegisterService(&AIBrainService_ServiceDesc, srv)
}

func _AIBrainService_SubmitAsyncTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitAsyncTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIBrainServiceServer).SubmitAsyncTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIBrainService_SubmitAsyncTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIBrainServiceServer).SubmitAsyncTask(ctx, req.(*SubmitAsyncTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIBrainService_GetAsyncTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAsyncTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIBrainServiceServer).GetAsyncTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIBrainService_GetAsyncTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIBrainServiceServer).GetAsyncTask(ctx, req.(*GetAsyncTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIBrainService_GetAsyncTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAsyncTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIBrainServiceServer).GetAsyncTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIBrainService_GetAsyncTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIBrainServiceServer).GetAsyncTasks(ctx, req.(*GetAsyncTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIBrainService_CancelAsyncTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelAsyncTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIBrainServiceServer).CancelAsyncTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIBrainService_CancelAsyncTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIBrainServiceServer).CancelAsyncTask(ctx, req.(*CancelAsyncTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIBrainService_UploadComfyUIInputFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadComfyUIInputFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIBrainServiceServer).UploadComfyUIInputFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIBrainService_UploadComfyUIInputFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIBrainServiceServer).UploadComfyUIInputFile(ctx, req.(*UploadComfyUIInputFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIBrainService_ChatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AIBrainServiceServer).ChatStream(m, &aIBrainServiceChatStreamServer{stream})
}

type AIBrainService_ChatStreamServer interface {
	Send(*ChatStreamResponse) error
	grpc.ServerStream
}

type aIBrainServiceChatStreamServer struct {
	grpc.ServerStream
}

func (x *aIBrainServiceChatStreamServer) Send(m *ChatStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _AIBrainService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIBrainServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIBrainService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIBrainServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIBrainService_ServiceDesc is the grpc.ServiceDesc for AIBrainService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIBrainService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aibrain.AIBrainService",
	HandlerType: (*AIBrainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitAsyncTask",
			Handler:    _AIBrainService_SubmitAsyncTask_Handler,
		},
		{
			MethodName: "GetAsyncTask",
			Handler:    _AIBrainService_GetAsyncTask_Handler,
		},
		{
			MethodName: "GetAsyncTasks",
			Handler:    _AIBrainService_GetAsyncTasks_Handler,
		},
		{
			MethodName: "CancelAsyncTask",
			Handler:    _AIBrainService_CancelAsyncTask_Handler,
		},
		{
			MethodName: "UploadComfyUIInputFile",
			Handler:    _AIBrainService_UploadComfyUIInputFile_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _AIBrainService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatStream",
			Handler:       _AIBrainService_ChatStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "v1/aibrain_service.proto",
}
