// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: v1/config_service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ConfigService_ReloadProviderConfig_FullMethodName   = "/aibrain.ConfigService/ReloadProviderConfig"
	ConfigService_GetProviderConfig_FullMethodName      = "/aibrain.ConfigService/GetProviderConfig"
	ConfigService_ValidateProviderConfig_FullMethodName = "/aibrain.ConfigService/ValidateProviderConfig"
)

// ConfigServiceClient is the client API for ConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigServiceClient interface {
	// ReloadProviderConfig 手动触发热加载
	ReloadProviderConfig(ctx context.Context, in *ReloadProviderConfigRequest, opts ...grpc.CallOption) (*ReloadProviderConfigResponse, error)
	// GetProviderConfig 获取当前Provider配置
	GetProviderConfig(ctx context.Context, in *GetProviderConfigRequest, opts ...grpc.CallOption) (*GetProviderConfigResponse, error)
	// ValidateProviderConfig 验证配置文件有效性
	ValidateProviderConfig(ctx context.Context, in *ValidateProviderConfigRequest, opts ...grpc.CallOption) (*ValidateProviderConfigResponse, error)
}

type configServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigServiceClient(cc grpc.ClientConnInterface) ConfigServiceClient {
	return &configServiceClient{cc}
}

func (c *configServiceClient) ReloadProviderConfig(ctx context.Context, in *ReloadProviderConfigRequest, opts ...grpc.CallOption) (*ReloadProviderConfigResponse, error) {
	out := new(ReloadProviderConfigResponse)
	err := c.cc.Invoke(ctx, ConfigService_ReloadProviderConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) GetProviderConfig(ctx context.Context, in *GetProviderConfigRequest, opts ...grpc.CallOption) (*GetProviderConfigResponse, error) {
	out := new(GetProviderConfigResponse)
	err := c.cc.Invoke(ctx, ConfigService_GetProviderConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) ValidateProviderConfig(ctx context.Context, in *ValidateProviderConfigRequest, opts ...grpc.CallOption) (*ValidateProviderConfigResponse, error) {
	out := new(ValidateProviderConfigResponse)
	err := c.cc.Invoke(ctx, ConfigService_ValidateProviderConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigServiceServer is the server API for ConfigService service.
// All implementations must embed UnimplementedConfigServiceServer
// for forward compatibility
type ConfigServiceServer interface {
	// ReloadProviderConfig 手动触发热加载
	ReloadProviderConfig(context.Context, *ReloadProviderConfigRequest) (*ReloadProviderConfigResponse, error)
	// GetProviderConfig 获取当前Provider配置
	GetProviderConfig(context.Context, *GetProviderConfigRequest) (*GetProviderConfigResponse, error)
	// ValidateProviderConfig 验证配置文件有效性
	ValidateProviderConfig(context.Context, *ValidateProviderConfigRequest) (*ValidateProviderConfigResponse, error)
	mustEmbedUnimplementedConfigServiceServer()
}

// UnimplementedConfigServiceServer must be embedded to have forward compatible implementations.
type UnimplementedConfigServiceServer struct {
}

func (UnimplementedConfigServiceServer) ReloadProviderConfig(context.Context, *ReloadProviderConfigRequest) (*ReloadProviderConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReloadProviderConfig not implemented")
}
func (UnimplementedConfigServiceServer) GetProviderConfig(context.Context, *GetProviderConfigRequest) (*GetProviderConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProviderConfig not implemented")
}
func (UnimplementedConfigServiceServer) ValidateProviderConfig(context.Context, *ValidateProviderConfigRequest) (*ValidateProviderConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateProviderConfig not implemented")
}
func (UnimplementedConfigServiceServer) mustEmbedUnimplementedConfigServiceServer() {}

// UnsafeConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigServiceServer will
// result in compilation errors.
type UnsafeConfigServiceServer interface {
	mustEmbedUnimplementedConfigServiceServer()
}

func RegisterConfigServiceServer(s grpc.ServiceRegistrar, srv ConfigServiceServer) {
	s.RegisterService(&ConfigService_ServiceDesc, srv)
}

func _ConfigService_ReloadProviderConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadProviderConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).ReloadProviderConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_ReloadProviderConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).ReloadProviderConfig(ctx, req.(*ReloadProviderConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_GetProviderConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProviderConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetProviderConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_GetProviderConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetProviderConfig(ctx, req.(*GetProviderConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_ValidateProviderConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateProviderConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).ValidateProviderConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_ValidateProviderConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).ValidateProviderConfig(ctx, req.(*ValidateProviderConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigService_ServiceDesc is the grpc.ServiceDesc for ConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aibrain.ConfigService",
	HandlerType: (*ConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReloadProviderConfig",
			Handler:    _ConfigService_ReloadProviderConfig_Handler,
		},
		{
			MethodName: "GetProviderConfig",
			Handler:    _ConfigService_GetProviderConfig_Handler,
		},
		{
			MethodName: "ValidateProviderConfig",
			Handler:    _ConfigService_ValidateProviderConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/config_service.proto",
}
