CREATE TABLE `va_model` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  `model_id` varchar(64) NOT NULL,
  `model_name` varchar(64) NOT NULL,
  `status` tinyint(4) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_va_model_model_id` (`model_id`),
  KEY `idx_va_model_deleted_at` (`deleted_at`)
) ENGINE=InnoDB AUTO_INCREMENT=49 DEFAULT CHARSET=utf8;

INSERT INTO va_model (model_id, model_name, status, created_at, updated_at) VALUES
('MODEL_GPT4O', 'MODEL_GPT4O', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MODEL_DOUBAO', 'MODEL_DOUBAO', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MODEL_GPT4', 'MODEL_GPT4', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MODEL_GPT4O_MINI', 'MODEL_GPT4O_MINI', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MODEL_GPTO1_PREVIEW', 'MODEL_GPTO1_PREVIEW', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MODEL_GPTO1_MINI', 'MODEL_GPTO1_MINI', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MODEL_DOUBAO_PRO', 'MODEL_DOUBAO_PRO', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MODEL_DOUBAO_VISION_PRO', 'MODEL_DOUBAO_VISION_PRO', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);