// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: invite.proto

package va_interface

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InviteService_GetInviteInfo_FullMethodName    = "/va_interface.InviteService/GetInviteInfo"
	InviteService_UseInviteCode_FullMethodName    = "/va_interface.InviteService/UseInviteCode"
	InviteService_GetInviteRecords_FullMethodName = "/va_interface.InviteService/GetInviteRecords"
)

// InviteServiceClient is the client API for InviteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InviteServiceClient interface {
	// 获取当前用户邀请信息
	GetInviteInfo(ctx context.Context, in *GetInviteInfoRequest, opts ...grpc.CallOption) (*GetInviteInfoResponse, error)
	// 使用邀请码
	UseInviteCode(ctx context.Context, in *UseInviteCodeRequest, opts ...grpc.CallOption) (*UseInviteCodeResponse, error)
	// 获取邀请记录列表（邀请人查看）
	GetInviteRecords(ctx context.Context, in *GetInviteRecordsRequest, opts ...grpc.CallOption) (*GetInviteRecordsResponse, error)
}

type inviteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInviteServiceClient(cc grpc.ClientConnInterface) InviteServiceClient {
	return &inviteServiceClient{cc}
}

func (c *inviteServiceClient) GetInviteInfo(ctx context.Context, in *GetInviteInfoRequest, opts ...grpc.CallOption) (*GetInviteInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInviteInfoResponse)
	err := c.cc.Invoke(ctx, InviteService_GetInviteInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inviteServiceClient) UseInviteCode(ctx context.Context, in *UseInviteCodeRequest, opts ...grpc.CallOption) (*UseInviteCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UseInviteCodeResponse)
	err := c.cc.Invoke(ctx, InviteService_UseInviteCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inviteServiceClient) GetInviteRecords(ctx context.Context, in *GetInviteRecordsRequest, opts ...grpc.CallOption) (*GetInviteRecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInviteRecordsResponse)
	err := c.cc.Invoke(ctx, InviteService_GetInviteRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InviteServiceServer is the server API for InviteService service.
// All implementations must embed UnimplementedInviteServiceServer
// for forward compatibility.
type InviteServiceServer interface {
	// 获取当前用户邀请信息
	GetInviteInfo(context.Context, *GetInviteInfoRequest) (*GetInviteInfoResponse, error)
	// 使用邀请码
	UseInviteCode(context.Context, *UseInviteCodeRequest) (*UseInviteCodeResponse, error)
	// 获取邀请记录列表（邀请人查看）
	GetInviteRecords(context.Context, *GetInviteRecordsRequest) (*GetInviteRecordsResponse, error)
	mustEmbedUnimplementedInviteServiceServer()
}

// UnimplementedInviteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInviteServiceServer struct{}

func (UnimplementedInviteServiceServer) GetInviteInfo(context.Context, *GetInviteInfoRequest) (*GetInviteInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInviteInfo not implemented")
}
func (UnimplementedInviteServiceServer) UseInviteCode(context.Context, *UseInviteCodeRequest) (*UseInviteCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UseInviteCode not implemented")
}
func (UnimplementedInviteServiceServer) GetInviteRecords(context.Context, *GetInviteRecordsRequest) (*GetInviteRecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInviteRecords not implemented")
}
func (UnimplementedInviteServiceServer) mustEmbedUnimplementedInviteServiceServer() {}
func (UnimplementedInviteServiceServer) testEmbeddedByValue()                       {}

// UnsafeInviteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InviteServiceServer will
// result in compilation errors.
type UnsafeInviteServiceServer interface {
	mustEmbedUnimplementedInviteServiceServer()
}

func RegisterInviteServiceServer(s grpc.ServiceRegistrar, srv InviteServiceServer) {
	// If the following call pancis, it indicates UnimplementedInviteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InviteService_ServiceDesc, srv)
}

func _InviteService_GetInviteInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInviteInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InviteServiceServer).GetInviteInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InviteService_GetInviteInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InviteServiceServer).GetInviteInfo(ctx, req.(*GetInviteInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InviteService_UseInviteCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UseInviteCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InviteServiceServer).UseInviteCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InviteService_UseInviteCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InviteServiceServer).UseInviteCode(ctx, req.(*UseInviteCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InviteService_GetInviteRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInviteRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InviteServiceServer).GetInviteRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InviteService_GetInviteRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InviteServiceServer).GetInviteRecords(ctx, req.(*GetInviteRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InviteService_ServiceDesc is the grpc.ServiceDesc for InviteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InviteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "va_interface.InviteService",
	HandlerType: (*InviteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInviteInfo",
			Handler:    _InviteService_GetInviteInfo_Handler,
		},
		{
			MethodName: "UseInviteCode",
			Handler:    _InviteService_UseInviteCode_Handler,
		},
		{
			MethodName: "GetInviteRecords",
			Handler:    _InviteService_GetInviteRecords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "invite.proto",
}
